language: objective-c
script:
  - xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=latest,name=iPhone 6' -project quve/quve.xcodeproj -scheme quve clean build test
