language: objective-c
xcode_project: quve/quve.xcodeproj
xcode_scheme: quve
xcode_sdk: iphonesimulator9.2
script:
  - xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= clean build -project quve/quve.xcodeproj -scheme quve -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
